export { default as Back } from './Back'
export { default as Check } from './Check'
export { default as Documents } from './Documents'
export { default as Download } from './Download'
export { default as Pen } from './Pen'
export { default as Stars } from './Stars'
export { default as World } from './World'
export { default as XIcon } from './XIcon'
